import type {RagId} from './rag';

export const datasetVersion = 'rag-lab-v3';
export type Example = {
 id:string; title:string; question:string; challenge:string; approaches:RagId[];
 grades:Record<string,number>; rationale:string; answer:string; inspect:string[]; observe:string;
};

// Suggested judgments and reference answers for fictional sources, not a benchmark.
export const examples:Example[] = [
 {id:'notice',title:'Current policy vs. archived guidance',question:'How much notice do tenants need to give for after-hours cooling?',challenge:'Version conflicts',approaches:['naive','rerank'],grades:{D01:2,D19:1},rationale:'D01 is the current request policy; D19 confirms that requests without the required notice are rejected. D12 is superseded and should not support a current answer.',answer:'Book after-hours heating or cooling in the tenant portal at least one business day before the event, naming the floor, start and end time. The archived three-day rule no longer applies.',inspect:['D01','D12','D19'],observe:'Check whether the archived three-day rule appears. Reranking pulls D12 into the top three because it shares the question’s words; text similarity does not enforce effective dates, and agreement between methods can repeat the same mistake.'},
 {id:'baseload',title:'Overnight energy, different wording',question:'Why is the building using so much electricity overnight?',challenge:'Alternate terminology',approaches:['multi','naive'],grades:{D10:2,D20:2,D06:1},rationale:'D10 reports the overnight baseload and its likely contributors; D20 documents a schedule override that kept an air handler running out-of-hours; D06 explains the lighting schedule.',answer:'Records point to air-handler schedules running past 22:00, lighting left on in unoccupied areas, and a past manual schedule override on AHU-8. These are leads to check against current schedules and meter data, not a proven cause.',inspect:['D10','D20','D06'],observe:'The question says electricity and overnight; the documents say baseload, out-of-hours and consumption. Compare the extra wordings Multi-query adds, and note that Hybrid’s keyword list brings in unrelated tenant documents instead of the override work order.'},
 {id:'f17',title:'Exact alarm code: F-17',question:'What should I check for alarm F-17 on AHU-7?',challenge:'Exact identifiers',approaches:['hybrid','agentic'],grades:{D04:2,D07:1},rationale:'D04 gives the F-17 checks; D07 identifies what AHU-7 serves. F-18 in D14 is a different fault.',answer:'F-17 is an airflow-proving fault. Check the fan belt and the airflow switch, then reset at the BMS. If F-17 returns within 24 hours, raise a priority work order.',inspect:['D04','D14','D07'],observe:'Compare the two alarm procedures. Naive ranks F-18 above F-17 because both share the same concepts; Hybrid’s exact-word list puts D04 first. The tokenizer splits F-17 into f and 17, so always check the full code in the source.'},
 {id:'chiller',title:'Chiller trip impact and who to call',question:'What is the impact of a CH-1 chiller trip and who should be called?',challenge:'Connected evidence',approaches:['graph','agentic'],grades:{D08:2,D09:2,D07:1},rationale:'D08 describes which air handlers lose chilled water; D09 gives the call order; D07 confirms AHU-7 depends on CH-1.',answer:'A CH-1 trip can stop cooling for AHU-7 and AHU-8, affecting the East and West wings. Call the plant team’s on-call engineer first, then notify the tenant help desk. Ownership identifies who to call; it does not establish impact on its own.',inspect:['D08','D09','D07'],observe:'Every approach returns the same three documents here, and Agentic routes the question to Graph because it mentions a trip and impact. Agreement does not verify the answer: check which document states the impact and which only names who to call.'},
 {id:'refund',title:'Related topic, unsupported refund',question:'Can we get a refund on after-hours cooling for a canceled event?',challenge:'Insufficient evidence',approaches:['naive','multi'],grades:{},rationale:'No document covers refunds or cancellations. Charge and dispute rules are related but do not answer the question.',answer:'The available documents do not say whether a canceled booking is refunded. Ask building management; billing disputes must be raised within 30 days of the statement.',inspect:['D02','D19'],observe:'A full row of related sources can still support no answer. The charge and dispute rules do not mention cancellations, and Multi-query’s extra wordings pull in unrelated comfort documents.'},
 {id:'unknown',title:'Unknown alarm: G-17',question:'What does alarm G-17 mean on AHU-7?',challenge:'Insufficient evidence',approaches:['hybrid','agentic'],grades:{},rationale:'G-17 is undocumented. F-17 cannot be treated as equivalent because the number matches.',answer:'G-17 is not documented in this collection. Confirm the exact alarm text and controller model with the mechanical team before applying any procedure.',inspect:['D04','D14'],observe:'Hybrid ranks the F-17 procedure first because the tokenizer splits G-17 and the number 17 matches. This is a limitation to recognise, not evidence that the two alarms mean the same thing.'},
 {id:'subtenant',title:'Subtenants vs. tenant requests',question:'Can a subtenant request after-hours cooling directly?',challenge:'Eligibility exceptions',approaches:['rerank','hybrid'],grades:{D11:2,D01:1},rationale:'D11 governs subtenants; D01 is the general tenant process, not an automatic subtenant entitlement.',answer:'No. Subtenants request after-hours HVAC through the head tenant’s registered contact, who submits and pays for it. Building management does not accept requests directly from subtenants.',inspect:['D11','D01'],observe:'Look for the subtenant rule ahead of the general booking policy. Hybrid and Reranking put D11 first; Naive ranks the rejected-requests note above it. A ranking improvement only helps if the first search includes the exception.'},
 {id:'hotwork',title:'Welding in the plant room tonight',question:'Can a contractor do a quick welding job in the plant room tonight?',challenge:'Policy scope',approaches:['rerank','naive'],grades:{D13:2,D05:1},rationale:'D13 requires a hot work permit even for short jobs, requested a business day ahead; D05 covers general contractor access.',answer:'Only with a hot work permit from the safety team, which must be requested at least one business day in advance, plus a fire watch for 60 minutes afterwards. Without an approved permit, the job cannot go ahead tonight.',inspect:['D13','D05'],observe:'Compare a broad contractor-access match with the rule that controls the answer. Hybrid and Graph put general site access (D05) first; the permit requirement in D13 decides whether the job can happen tonight.'},
 {id:'f18',title:'Similar alarm: F-18',question:'What should I check for alarm F-18 on AHU-7?',challenge:'Similar procedures',approaches:['hybrid','rerank'],grades:{D14:2,D07:1},rationale:'D14 addresses the loaded filter. The F-17 checks in D04 do not fix F-18.',answer:'F-18 means high filter differential pressure, usually a loaded filter. Replace the filters using MP-42 revision 3; resetting the alarm alone does not clear it.',inspect:['D14','D04','D15'],observe:'Only the alarm code changes from the F-17 example. Hybrid ranks the F-17 procedure above F-18 because the two share almost every word; Reranking puts D14 first. Check that ranking preserves the distinction.'},
 {id:'thermostat',title:'Faulty thermostat vs. fit-out budget',question:'Can we replace a faulty thermostat in our suite ourselves?',challenge:'Overlapping topics',approaches:['rerank','multi'],grades:{D16:2,D03:1},rationale:'D16 makes suite thermostats base-building equipment that tenants must not replace; D03 only explains how to use them.',answer:'No. Suite thermostats are base-building equipment maintained by facilities. Report the fault through a work order; tenants must not replace, move or rewire them.',inspect:['D16','D03','D15'],observe:'Thermostat vocabulary appears in several documents. Naive and Multi-query fill the list with comfort troubleshooting; Reranking lifts the base-building rule (D16) that actually answers the question.'},
 {id:'setpoint',title:'Meeting room below the standard range',question:'Can we lower our meeting room setpoint to 66°F?',challenge:'Exception workflow',approaches:['multi','rerank'],grades:{D17:2,D16:1},rationale:'D17 sets the 70–75°F range and the approval route; D16 explains that facilities maintain suite controls.',answer:'66°F is outside the standard 70–75°F range. It needs a facilities comfort assessment and building manager approval before the setpoint changes.',inspect:['D17','D16','D15'],observe:'Every approach finds the setpoint policy first. The answer depends on its approval step, not just the 70–75°F range, so read the whole passage rather than counting matches.'},
 {id:'extended',title:'Event longer than eight hours',question:'Can we book after-hours cooling for an event longer than eight hours?',challenge:'Approval exceptions',approaches:['hybrid','rerank'],grades:{D18:2,D01:1},rationale:'D18 specifies the exception; D01 is the standard booking rule.',answer:'Yes, with written building manager approval before the booking is confirmed. Attach the event details to the portal request; standard portal confirmation does not approve an extended booking.',inspect:['D18','D01','D19'],observe:'Check that both the standard booking rule and the eight-hour exception are present. Naive returns the exception alongside the archived policy and the rejection note, but not the current booking rule (D01).'},
 {id:'commsroom',title:'Indirect impact on comms room 305',question:'How could a CH-1 chiller trip affect comms room 305?',challenge:'Multiple dependencies',approaches:['graph','agentic'],grades:{D08:2,D07:2,D21:2},rationale:'D08 and D07 establish CH-1 to AHU-7; D21 establishes AHU-7 to comms room 305. All three are needed for the indirect chain.',answer:'If CH-1 stops supplying chilled water, AHU-7 loses cooling, and so does the fan coil serving comms room 305. The room warms and network equipment may shut down. This is conditional exposure, not proof that every trip causes an outage.',inspect:['D08','D07','D21'],observe:'Graph starts from D09 and follows one hop, so it never reaches D21, even at Top K = 5. Other approaches find D21 only at rank 4 or 5 through shared words. Inspect the source chain and try bounded traversal in Graph & tools.'},
 {id:'moveout',title:'End access when a tenant leaves',question:'How do we deactivate access cards when a tenant moves out?',challenge:'Task-specific evidence',approaches:['hybrid','agentic'],grades:{D23:2,D05:1},rationale:'D23 gives the move-out procedure; D05 describes baseline site access controls.',answer:'The tenant contact submits a move-out notice with the final day. Security deactivates all access cards and portal accounts at the end of that day, facilities records final meter readings, and physical keys are collected.',inspect:['D23','D05'],observe:'Every approach finds the move-out checklist first. The fixed Agentic rules do not recognise this task type and route it to Naive; only Graph’s links bring in the baseline access policy (D05).'},
 {id:'movein',title:'Prepare for a new tenant',question:'How do we get a new tenant ready before move-in day?',challenge:'Narrow matches',approaches:['naive','rerank'],grades:{D24:2,D03:2,D01:1},rationale:'D24 covers pre-move-in setup; D03 covers move-in day; D01 explains the after-hours booking process tenants learn on arrival.',answer:'Confirm the move-in date and registered contacts, prepare access cards, register the contacts in the tenant portal and schedule a comfort walkthrough for the first week. On move-in day, hand over cards and portal logins and show the thermostats.',inspect:['D24','D03','D01'],observe:'Naive ranks a suite-equipment note first because it shares one narrow concept with the question, and misses the setup checklist. Reranking by the question’s words brings D24 and D03 to the top.'},
];

// What each suggested approach does with an example at Top K = 3 over all documents.
// tests/rag.test.ts checks every document cited here against the live ranking.
export type Lesson = {kind:'works'|'limit'; note:string; expect:string[]};
export const lessons:Record<string,Partial<Record<RagId,Lesson>>> = {
 notice:{naive:{kind:'works',expect:['D19','D01'],note:'Naive finds the current booking rule (D01) and the rejection note (D19). The archived three-day rule (D12) stays out of the top three.'},
  rerank:{kind:'limit',expect:['D01','D12'],note:'Reranking puts the current rule (D01) first, but lifts the archived three-day rule (D12) to rank 2 because it shares the question’s words. Word overlap cannot tell which policy is current.'}},
 baseload:{multi:{kind:'works',expect:['D20','D10','D06'],note:'The extra wordings add terms the documents use, such as baseload and consumption. The override work order (D20), the energy audit (D10) and the lighting schedule (D06) all come back.'},
  naive:{kind:'works',expect:['D20','D10','D06'],note:'Even without extra wordings, Naive finds the override work order (D20), the energy audit (D10) and the lighting schedule (D06). One search is sometimes enough.'}},
 f17:{hybrid:{kind:'works',expect:['D04','D14'],note:'The exact-word search matches F-17, so the F-17 procedure (D04) ranks first. The F-18 procedure (D14) is a near tie, so check the code in each passage.'},
  agentic:{kind:'works',expect:['D04'],note:'The question contains an alarm code, so the rules pick Hybrid, which ranks the F-17 procedure (D04) first.'}},
 chiller:{graph:{kind:'works',expect:['D09','D07','D08'],note:'Graph starts at the trip response (D09) and follows its links to AHU-7 (D07) and CH-1 (D08). Who to call and what is affected arrive together.'},
  agentic:{kind:'works',expect:['D09','D07','D08'],note:'The question mentions a trip and impact, so the rules pick Graph. It returns the trip response (D09) with the linked equipment (D07, D08).'}},
 refund:{naive:{kind:'limit',expect:['D02','D18','D12'],note:'No document covers refunds, yet Naive still returns three related passages: charges (D02), extended bookings (D18) and the archived policy (D12). Search returns its closest matches even when none answers.'},
  multi:{kind:'limit',expect:['D17','D15','D02'],note:'No document covers refunds. The extra wordings about hours and cooling put two unrelated comfort documents (D17, D15) ahead of the charges policy (D02).'}},
 unknown:{hybrid:{kind:'limit',expect:['D04'],note:'G-17 is not documented, but the F-17 procedure (D04) ranks first: the search splits G-17 into g and 17, and 17 matches. A similar code is not the same alarm.'},
  agentic:{kind:'limit',expect:['D04','D14'],note:'The rules see an alarm code and pick Hybrid, which returns the F-17 and F-18 procedures. The evidence check counts sources; it does not notice that G-17 is never mentioned.'}},
 subtenant:{rerank:{kind:'works',expect:['D11','D01'],note:'The re-sort puts the subtenant rule (D11) first, ahead of the general booking policy (D01). The exception that answers the question leads.'},
  hybrid:{kind:'works',expect:['D11','D01'],note:'The exact word subtenant lifts the subtenant rule (D11) to the top, ahead of the general booking policy (D01).'}},
 hotwork:{rerank:{kind:'works',expect:['D13','D05'],note:'The hot work permit rule (D13) ranks first, ahead of general contractor access (D05). The permit rule decides whether the job can happen tonight.'},
  naive:{kind:'works',expect:['D13','D05','D08'],note:'Naive puts the hot work permit rule (D13) first and contractor access (D05) second. The chiller document (D08) at rank 3 matches only because it mentions the plant.'}},
 f18:{hybrid:{kind:'limit',expect:['D04','D14'],note:'Hybrid ranks the F-17 procedure (D04) above F-18 (D14), because the two passages share almost every word. Only one character of the code differs.'},
  rerank:{kind:'works',expect:['D14','D04'],note:'The re-sort puts the F-18 procedure (D14) first, just ahead of F-17 (D04). The margin is tiny, so read the code in each passage.'}},
 thermostat:{rerank:{kind:'works',expect:['D16','D15'],note:'The re-sort lifts the base-building rule (D16), which says tenants must not replace thermostats, above the comfort troubleshooting note (D15).'},
  multi:{kind:'limit',expect:['D17','D15','D12'],note:'The extra wordings add comfort and fault terms, filling the list with setpoint and troubleshooting documents (D17, D15, D12). The rule that answers the question (D16) is missing.'}},
 setpoint:{multi:{kind:'works',expect:['D17'],note:'Multi-query adds one wording about comfort and setpoints, and the setpoint policy (D17) ranks first. Read its approval step, not just the 70–75°F range.'},
  rerank:{kind:'works',expect:['D17'],note:'The setpoint policy (D17) ranks first. The answer depends on its approval step, not just the 70–75°F range, so read the whole passage.'}},
 extended:{hybrid:{kind:'works',expect:['D18','D01'],note:'The eight-hour exception (D18) ranks first and the standard booking rule (D01) second, so both parts of the answer are present.'},
  rerank:{kind:'works',expect:['D18','D01','D12'],note:'The re-sort keeps the eight-hour exception (D18) first and brings the standard booking rule (D01) to rank 2. The archived policy (D12) still appears at rank 3.'}},
 commsroom:{graph:{kind:'limit',expect:['D09','D07','D08'],note:'Graph starts from the trip response (D09) and follows one link to D07 and D08. Comms room 305 (D21) is two links away, so it never appears, even at Top K 5.'},
  agentic:{kind:'limit',expect:['D09','D07','D08'],note:'The question mentions a trip, so the rules pick Graph, which stops one link short of comms room 305 (D21).'}},
 moveout:{hybrid:{kind:'works',expect:['D23','D24','D03'],note:'The move-out checklist (D23) ranks first. The move-in documents (D24, D03) follow because they share the tenant and access-card words.'},
  agentic:{kind:'works',expect:['D23','D24','D03'],note:'The rules do not recognise this task, so they fall back to Naive, which still puts the move-out checklist (D23) first.'}},
 movein:{naive:{kind:'limit',expect:['D16','D11','D03'],note:'Naive ranks the suite-equipment note (D16) first because it shares one narrow concept, and the setup checklist (D24) misses the top three.'},
  rerank:{kind:'works',expect:['D24','D03'],note:'Re-sorting by the question’s words brings the setup checklist (D24) and the move-in guide (D03) to the top.'}},
};

// Playground suggestions: strengths first, then a limit worth seeing.
export const playgroundPicks:Record<RagId,string[]> = {
 naive:['notice','baseload','refund'],
 hybrid:['f17','subtenant','unknown'],
 rerank:['f18','thermostat','notice'],
 multi:['baseload','thermostat','refund'],
 graph:['chiller','commsroom'],
 agentic:['f17','chiller','unknown'],
};
