export type RagId = 'naive' | 'hybrid' | 'rerank' | 'multi' | 'graph' | 'agentic';
export const patterns: {id: RagId; name: string; short: string; description: string; use: string; tradeoff: string; steps: string[]; stepNotes: string[]}[] = [
  {id:'naive',name:'Naive RAG',short:'One search by meaning',description:'Search once for the documents closest in meaning to the question, and use the top few as evidence.',use:'Tenant handbooks, building FAQs and other questions one passage can answer.',tradeoff:'Simple and fast, but one search can miss exact codes such as F-17, or context spread across several documents.',steps:['Question','Concept search','Top documents','Cite evidence'],stepNotes:['You ask in everyday words.','Score each document by how many of the question’s concepts it shares.','Keep the highest-scoring documents, up to Top K.','Show those passages as evidence, each with its document ID.']},
  {id:'hybrid',name:'Hybrid RAG',short:'Meaning + exact words',description:'Run a meaning search and an exact-word search side by side, then merge the two ranked lists.',use:'Equipment support where alarm codes and plain-language symptoms appear together.',tradeoff:'Needs two search indexes and a rule for merging their rankings. How much it helps depends on your documents and questions.',steps:['Question','Concept + keyword','Merge rankings','Cite evidence'],stepNotes:['A question can mix an idea with an exact term, such as “alarm F-17 on AHU-7”.','Search twice: once by shared concepts, once by matching words.','Merge the two lists. Documents that both searches found move up.','Show the merged evidence with document IDs.']},
  {id:'rerank',name:'Reranking RAG',short:'Shortlist, then re-sort',description:'Pull a broad shortlist first, then score each candidate again and re-sort the list.',use:'Procedures and policies with many similar documents and subtle exceptions.',tradeoff:'The second pass adds time. Production systems usually re-sort with a dedicated reranking model, not a fixed weighting.',steps:['Question','Shortlist','Re-sort','Cite evidence'],stepNotes:['Start with the question.','Pull up to eight candidates with a quick concept search.','Score each candidate again, weighting the question’s exact words more heavily, then re-sort.','Show the top of the re-sorted list.']},
  {id:'multi',name:'Multi-query RAG',short:'Several wordings',description:'Search with several wordings of the question, then combine what each search finds.',use:'Investigations where occupants, engineers and auditors describe the same issue differently.',tradeoff:'Extra wordings can find documents that use different words, but they can also pull in unrelated ones. Check what each wording adds.',steps:['Question','Reword','Merge results','Cite evidence'],stepNotes:['Documents may use other words than you do, such as “baseload” for “overnight electricity”.','Add up to two extra wordings from a small synonym list.','Search each wording, drop duplicates and keep each document’s best score.','Show the combined evidence.']},
  {id:'graph',name:'Graph RAG',short:'Follow document links',description:'Find the best starting document, then follow its links to connected documents.',use:'Tracing equipment dependencies, ownership and outage impact.',tradeoff:'Someone has to build and maintain the links. This demo uses a small, hand-made set of links between documents.',steps:['Question','Find a start','Follow links','Cite evidence'],stepNotes:['Useful when an answer spans connected things, such as a chiller and the air handlers it supplies.','Find the single best-matching document to start from.','Add the documents it links to, one step away.','Show the starting document and its neighbors.']},
  {id:'agentic',name:'Agentic RAG',short:'Pick a method, check, retry',description:'Choose a search method for the question, check whether enough came back, and search again if not.',use:'Assistants handling different question types and incomplete initial evidence.',tradeoff:'Each extra decision adds cost and makes results harder to predict. This demo uses fixed rules in place of an AI model.',steps:['Question','Pick a method','Check & retry','Cite evidence'],stepNotes:['The question decides which method to try first.','Questions about outages, trips, failures, impact, dependencies or ownership use Graph; alarm codes such as F-17 use Hybrid; everything else uses Naive.','If fewer than two sources come back, search once more with Hybrid.','Show the evidence. Fixed rules make these choices here, not an AI model.']},
];
export type Document = {id: string; title: string; category: string; text: string; links: string[]};
// Authored fictional fixtures: see assumption A1 in lib/research.ts.
export const documents: Document[] = [
 {id:'D01',title:'After-hours HVAC requests',category:'Tenant services',text:'Tenants request after-hours heating or cooling through the tenant portal at least one business day before the event. Each request names the floor, start time and end time. Building management confirms the booking by email.',links:['D02','D18']},
 {id:'D02',title:'After-hours HVAC charges',category:'Tenant services',text:'After-hours heating and cooling is billed at $85 per floor per hour, with a two-hour minimum. Charges appear on the next monthly service-charge statement. Raise billing disputes with building management within 30 days of the statement.',links:['D01','D19']},
 {id:'D03',title:'New tenant welcome guide',category:'Tenant services',text:'On move-in day, each registered tenant contact receives an access card and a tenant portal login. Building management explains how to book after-hours HVAC, and the facilities team shows the tenant how to use the suite thermostats.',links:['D01','D16','D24']},
 {id:'D04',title:'Alarm F-17 on AHU-7',category:'HVAC & plant',text:'Alarm F-17 on AHU-7 is an airflow-proving fault: the supply fan is commanded on but the airflow switch does not prove flow. Check the fan belt and the airflow switch, then reset the alarm at the BMS. If F-17 returns within 24 hours, raise a priority work order.',links:['D07','D14']},
 {id:'D05',title:'Contractor site access',category:'Safety & security',text:'Contractors sign in at the security desk, wear a visible badge and are escorted in plant rooms. Work on live electrical or mechanical systems needs an approved permit to work. Never prop open fire doors.',links:['D13','D23']},
 {id:'D06',title:'Lighting schedules',category:'Energy & controls',text:'Common-area lighting runs from 07:00 to 19:00 on weekdays and dims to 30% outside those hours. Occupancy sensors turn tenant floor lighting off after 20 minutes without movement.',links:['D10']},
 {id:'D07',title:'AHU-7 overview',category:'HVAC & plant',text:'AHU-7 supplies conditioned air to the East wing, floors 3 and 4. AHU-7 depends on chiller CH-1 for chilled water. The mechanical team maintains AHU-7 and responds to its alarms.',links:['D08','D09','D21']},
 {id:'D08',title:'Chiller CH-1',category:'HVAC & plant',text:'Chiller CH-1 provides chilled water to AHU-7 and AHU-8. The plant team owns CH-1. A CH-1 trip can stop cooling for both air handlers, affecting the East and West wings.',links:['D07','D09']},
 {id:'D09',title:'Chiller trip response',category:'HVAC & plant',text:'For a CH-1 trip, call the plant team’s on-call engineer first, then notify the tenant help desk about comfort impact in the East and West wings. Log the incident in the building operations channel.',links:['D07','D08']},
 {id:'D10',title:'Energy audit EA-12',category:'Energy & controls',text:'Energy audit EA-12 found that Harbor Tower’s overnight baseload is 40% of its daytime peak demand. Likely contributors are air-handler time schedules that run past 22:00 and tenant lighting left on in unoccupied areas.',links:['D06','D20']},
 {id:'D11',title:'Subtenant service requests',category:'Tenant services',text:'Subtenants do not have their own tenant portal accounts. They request after-hours HVAC and other services through the head tenant’s registered contact, who submits and pays for the request. Building management does not accept requests directly from subtenants.',links:['D01','D02']},
 {id:'D12',title:'After-hours HVAC requests — archived 2024',category:'Tenant services',text:'ARCHIVED: effective in 2024 and superseded by the current after-hours HVAC request policy D01. Tenants had to request after-hours heating or cooling at least three business days in advance. Do not use this version for current bookings.',links:['D01']},
 {id:'D13',title:'Hot work permits',category:'Safety & security',text:'Welding, cutting, grinding or brazing anywhere in the building requires a hot work permit from the safety team, even for a short job. A trained fire watch stays on site for 60 minutes after the work ends. Request the permit at least one business day in advance.',links:['D05']},
 {id:'D14',title:'Alarm F-18 on AHU-7',category:'HVAC & plant',text:'Alarm F-18 on AHU-7 means the filter differential pressure is above its limit, which usually indicates a loaded filter. Replace the filters using maintenance procedure MP-42 revision 3. Resetting the alarm alone does not clear a loaded filter.',links:['D04','D07']},
 {id:'D15',title:'Warm room without an alarm',category:'HVAC & plant',text:'A room that feels warm with no active alarm may have a local setpoint change, open blinds or higher occupancy. Check the thermostat setpoint and recent BMS trends before raising a work order. A comfort complaint alone is not proof that equipment has failed.',links:['D16','D17']},
 {id:'D16',title:'Base-building equipment in suites',category:'Tenant services',text:'A thermostat, VAV box or sensor in a tenant suite is base-building equipment maintained by the facilities team. Report a faulty thermostat through a work order; tenants must not replace, move or rewire it. Tenant fit-out budgets do not cover base-building controls.',links:['D03','D17']},
 {id:'D17',title:'Setpoint change requests',category:'Energy & controls',text:'Suite temperature setpoints stay within the standard 70–75°F range. A request outside that range, such as a cooler meeting room, needs a facilities comfort assessment and building manager approval before the setpoint changes.',links:['D15','D16']},
 {id:'D18',title:'Extended after-hours HVAC',category:'Tenant services',text:'After-hours HVAC bookings longer than eight hours, or on public holidays, need written approval from the building manager before they are confirmed. Attach the event details to the portal request. Standard portal confirmation does not approve an extended booking.',links:['D01','D19']},
 {id:'D19',title:'Rejected HVAC requests',category:'Tenant services',text:'The tenant portal rejects after-hours requests that lack a floor, an end time or the required notice. Correct the request and resubmit it. A rejected request is not an automatic exception; contact building management if the event is urgent.',links:['D01','D18','D02']},
 {id:'D20',title:'Work order WO-305: schedule override',category:'Energy & controls',text:'Work order WO-305 found that a manual schedule override had kept AHU-8 running out-of-hours for three weeks. The override was removed and the normal time schedule restored. Check for active overrides when investigating unexpected overnight consumption.',links:['D10','D08']},
 {id:'D21',title:'Comms room 305 cooling',category:'HVAC & plant',text:'Comms room 305 is cooled by a fan coil on AHU-7’s chilled-water branch. If AHU-7 loses chilled water, the room temperature rises and network equipment may shut down to protect itself. IT operations owns the equipment in room 305.',links:['D07','D22']},
 {id:'D22',title:'Building escalation directory',category:'Safety & security',text:'Call the plant team for chiller trips, the mechanical team for air-handler alarms, IT operations for comms room alerts and the tenant help desk for comfort complaints. Coordinate in the building operations channel. Ownership tells you who to call; it does not by itself prove a system is affected.',links:['D08','D07','D21','D09']},
 {id:'D23',title:'Tenant move-out checklist',category:'Safety & security',text:'When a tenant moves out, their contact submits a move-out notice with the final day. Security deactivates all access cards and tenant portal accounts at the end of that day, and facilities records final meter readings. Collect physical keys; deactivating cards alone does not end all access.',links:['D05','D03']},
 {id:'D24',title:'New tenant setup',category:'Tenant services',text:'Before move-in day, the building manager confirms the move-in date and the tenant’s registered contacts. Security prepares access cards, facilities registers the contacts in the tenant portal, and the mechanical team schedules a comfort walkthrough for the first week.',links:['D03','D23']},
];
const stop = new Set('a an the is are to of for and in on can how what do does i my with me about when which our has it'.split(' '));
const tokens = (text: string) => text.toLowerCase().match(/[a-z0-9]+/g)?.filter(x=>!stop.has(x)) ?? [];
const groups = ['hours overnight evening night weekend tonight','cooling heating hvac temperature comfort setpoint thermostat thermostats warm cold','charge charges billed refund cost rate','alarm fault faulty error trip failure','chiller chilled water plant','ahu air handler airflow fan filter','tenant tenants subtenant subtenants occupant','access card cards badge keys security','electricity energy baseload consumption demand','contractor contractors permit welding','outage impact affect affected depends dependency','move moves moving onboarding welcome setup'];
function vector(text: string) {const words=tokens(text); return groups.map(g=>g.split(' ').filter(w=>words.includes(w)).length);}
function semantic(q:string,d:Document) {const a=vector(q), b=vector(d.title+' '+d.text);const denom=Math.hypot(...a)*Math.hypot(...b);return denom ? a.reduce((s,v,i)=>s+v*b[i],0)/denom : 0;}
function keyword(q:string,d:Document) {const words=tokens(q), content=tokens(d.title+' '+d.text); return words.length ? words.filter(w=>content.includes(w)).length/words.length : 0;}
const plural = (n:number, word:string) => `${n} ${word}${n===1?'':'s'}`;
export type Hit = {doc:Document; score:number; reason:string};
export type Result = {hits:Hit[]; trace:string[]; queries:string[]; answer:string; route?:string; retried?:boolean};
export function retrieve(id:RagId,question:string,topK=3,category='All documents'):Result {
 const q=question.trim(); const pool=documents.filter(d=>category==='All documents'||d.category===category);
 const rank=(query:string,kind:'semantic'|'keyword')=>pool.map(doc=>({doc,score:kind==='semantic'?semantic(query,doc):keyword(query,doc),reason:kind==='semantic'?'Concept-vector similarity':'Exact keyword overlap'})).filter(h=>h.score>0).sort((a,b)=>b.score-a.score);
 const fuse=(query:string)=>{const a=rank(query,'semantic'),b=rank(query,'keyword');return pool.map(doc=>({doc,score:[a,b].reduce((s,list)=>{const i=list.findIndex(h=>h.doc.id===doc.id);return s+(i<0?0:1/(60+i+1));},0),reason:'Reciprocal rank fusion (k = 60)'})).filter(h=>h.score>0).sort((a,b)=>b.score-a.score);};
 let hits:Hit[]=[];let queries=[q];let trace:string[]=[];let route:string|undefined;let retried=false;
 if(!q)return {hits:[],queries:[],trace:['Enter a question to begin.'],answer:'Enter a question to explore the knowledge base.'};
 if(id==='naive'){hits=rank(q,'semantic');trace=['Encode the question and documents as small, hand-built concept vectors.','Rank documents by cosine similarity.'];}
 if(id==='hybrid'){hits=fuse(q);trace=['Run concept-vector retrieval and exact keyword retrieval independently.','Combine both rankings with reciprocal rank fusion: Σ 1 / (60 + rank). This constant is separate from Top K.'];}
 if(id==='rerank'){const candidates=rank(q,'semantic').slice(0,8);hits=candidates.map(h=>({...h,score:0.35*h.score+0.65*keyword(q,h.doc),reason:'Heuristic rerank: 35% concept + 65% keyword'})).sort((a,b)=>b.score-a.score);trace=[`Retrieve ${plural(candidates.length,'candidate')} using concept similarity.`,'Rerank with query-specific keyword overlap. A production system may use a cross-encoder.'];}
 if(id==='multi'){const expanded=groups.filter(g=>g.split(' ').some(w=>tokens(q).includes(w))).map(g=>q+' '+g);queries=[q,...expanded.slice(0,2)];const merged=new Map<string,Hit>();for(const query of queries)for(const h of rank(query,'semantic')){const old=merged.get(h.doc.id);if(!old||h.score>old.score)merged.set(h.doc.id,{...h,reason:'Best similarity across expanded queries'});}hits=[...merged.values()].sort((a,b)=>b.score-a.score);trace=[queries.length>1?`Create ${queries.length} queries using a small synonym dictionary.`:'No dictionary group matched; search the original wording only.', 'Search each query, deduplicate documents, and keep each document’s best score.'];}
 if(id==='graph'){const seeds=fuse(q).slice(0,1);hits=[...seeds];for(const seed of seeds)for(const link of seed.doc.links){const doc=pool.find(d=>d.id===link);if(doc&&!hits.some(h=>h.doc.id===link))hits.push({doc,score:seed.score*0.8,reason:`One-hop relationship from ${seed.doc.id}`});}trace=[`Find entry document: ${seeds[0]?.doc.id??'none'}.`,'Follow outgoing document links one hop; linked scores are 0.8 × the seed score, an illustrative scoring rule.'];}
 if(id==='agentic'){route=/outage|trip|fail|depend|impact|affect|owns/i.test(q)?'graph':/\b[a-z]-\d+\b/i.test(q)?'hybrid':'naive';const first=retrieve(route as RagId,q,topK,category);hits=first.hits;// Drop the routed call's final selection step; the shared step below records it once.
 trace=[`Rule-based planner chooses ${route} retrieval.`,...first.trace.slice(0,-1)];if(hits.length<2){hits=fuse(q);retried=true;trace.push('Evidence check: fewer than two sources after Top K. Retry with hybrid retrieval. This counts sources, not answerability.');}else trace.push('Evidence check: multiple sources available; return evidence. This counts sources, not relevance or answerability.');}
 hits=hits.slice(0,Math.max(1,Math.min(5,topK)));trace.push(`Select ${plural(hits.length,'source document')} within the selected collection.`);
 const answer=hits.length?hits.map(h=>`${h.doc.text} [${h.doc.id}]`).join('\n\n'):'No matching evidence was found in this collection. Try a different question or select all documents.';
 return {hits,trace,queries,answer,route,retried};
}
