import {documents, type RagId} from './rag';
import {examples} from './examples';

// Editorial review date, not an automated verification or freshness guarantee.
export const reviewedOn = '2026-10-01';
// Only arXiv papers: open access, no vendor pages.
export const sourceGroups = ['Retrieval methods','Graphs, agents and buildings','Evaluation and context','Security and operations'] as const;
type Reference = {title:string;url:string;group:typeof sourceGroups[number];note:string;usedIn:string[]};
export const references = {
 rag: {title:'Lewis et al. (2020): Retrieval-Augmented Generation',url:'https://arxiv.org/abs/2005.11401',group:'Retrieval methods',note:'The original RAG paper: a retriever supplies passages to a text generator.',usedIn:['All approaches']},
 bm25: {title:'Thakur et al. (2021): BEIR',url:'https://arxiv.org/abs/2104.08663',group:'Retrieval methods',note:'Across 18 datasets, BM25 keyword search is a robust baseline. Our BM25 is a small local implementation.',usedIn:['Model comparison lab']},
 fusion: {title:'Bruch et al. (2022): Fusion Functions for Hybrid Retrieval',url:'https://arxiv.org/abs/2210.11934',group:'Retrieval methods',note:'Studies reciprocal rank fusion for merging keyword and meaning search, and finds it sensitive to its settings.',usedIn:['Hybrid RAG']},
 rerank: {title:'Nogueira & Cho (2019): Passage Re-ranking with BERT',url:'https://arxiv.org/abs/1901.04085',group:'Retrieval methods',note:'Rescore retrieved passages with a model that reads question and passage together. Our 35/65 weights are illustrative.',usedIn:['Reranking RAG','Model comparison lab']},
 multi: {title:'Rackauckas (2024): RAG-Fusion',url:'https://arxiv.org/abs/2402.03367',group:'Retrieval methods',note:'Generate several queries, search each and fuse the rankings. Here, dictionary groups stand in for generated queries.',usedIn:['Multi-query RAG']},
 graph: {title:'Edge et al. (2024): A Graph RAG Approach',url:'https://arxiv.org/abs/2404.16130',group:'Graphs, agents and buildings',note:'Builds an entity graph with community summaries. This app follows authored one-hop links instead.',usedIn:['Graph RAG','Graph & tools lab']},
 agents: {title:'Yao et al. (2022): ReAct',url:'https://arxiv.org/abs/2210.03629',group:'Graphs, agents and buildings',note:'A model alternates reasoning with tool calls. Our routing is a fixed rule, not a model.',usedIn:['Agentic RAG','Graph & tools lab']},
 buildings: {title:'Quinn & McArthur (2022): Comparison of Brick and Project Haystack',url:'https://arxiv.org/abs/2205.05521',group:'Graphs, agents and buildings',note:'Compares the two main open data models for building equipment, sensors and spaces.',usedIn:['Production blueprint']},
 evaluation: {title:'Wang et al. (2013): NDCG Type Ranking Measures',url:'https://arxiv.org/abs/1304.6480',group:'Evaluation and context',note:'Analyzes nDCG, the graded ranking score the Evaluation lab reports.',usedIn:['Evaluation lab']},
 citations: {title:'Gao et al. (2023): Generating Text with Citations',url:'https://arxiv.org/abs/2305.14627',group:'Evaluation and context',note:'Scores citation quality separately from answer correctness.',usedIn:['Evaluation lab','Model comparison lab']},
 context: {title:'Liu et al. (2023): Lost in the Middle',url:'https://arxiv.org/abs/2307.03172',group:'Evaluation and context',note:'In the studied models, facts in the middle of a long prompt were used less reliably.',usedIn:['Ingestion lab']},
 injection: {title:'Greshake et al. (2023): Indirect Prompt Injection',url:'https://arxiv.org/abs/2302.12173',group:'Security and operations',note:'Instructions hidden in retrieved text can take over an LLM app. Treat passages as data, not commands.',usedIn:['Security lab','Production blueprint']},
 poisoning: {title:'Zou et al. (2024): PoisonedRAG',url:'https://arxiv.org/abs/2402.07867',group:'Security and operations',note:'A few planted passages can steer a RAG system’s answers.',usedIn:['Security lab','Production blueprint']},
 capacity: {title:'Hill (2019): Three Other Models of Computer System Performance',url:'https://arxiv.org/abs/1901.02926',group:'Security and operations',note:'Includes Little’s Law: work in progress = arrival rate × time in system.',usedIn:['Operations lab','Production blueprint']},
} satisfies Record<string,Reference>;

export const patternResearch: Record<RagId,{limit:string}> = {
 naive:{limit:'Method details: twelve hand-written concept dimensions, not learned embeddings. Related dictionary words may score alike even when their meanings differ; a match does not establish relevance.'},
 hybrid:{limit:'Method details: cosine ranking + token-overlap ranking, fused with k = 60. This is not BM25. Lowercase letter/number tokens split F-17 into f and 17, so full identifiers are not enforced.'},
 rerank:{limit:'Method details: at most eight concept-search candidates, rescored as 0.35 × cosine + 0.65 × token overlap. These weights are not calibrated; missed first-stage documents cannot be recovered.'},
 multi:{limit:'Method details: append up to two matching dictionary groups in dictionary order. These are not generated paraphrases. Merge by maximum cosine score; neither broader coverage nor better recall is guaranteed.'},
 graph:{limit:'Method details: one hybrid seed, one outgoing hop, and linked score = 0.8 × seed score. Links are authored associations, not verified causal dependencies. Equal linked scores keep stored link order; Top K can omit neighbors.'},
 agentic:{limit:'Method details: text containing outage, trip, fail, depend, impact, affect or owns routes to graph first; otherwise a single-letter code like F-17 routes to hybrid, then naive is the default. Fewer than two initial results triggers one hybrid retry. For nonempty questions, Top K = 1 therefore always retries. Source count does not check answerability.'},
};

export const assumptions = [
 {id:'A1',title:'Fictional source material',origin:'lib/rag.ts · documents; lib/building-scenarios.ts · scenarios',text:`Harbor Tower and all ${documents.length} of its documents were invented for this app: tenant rules, charges and deadlines, alarm codes F-17 and F-18, equipment, ownership, topology, readings, work orders and example answers. D01–D24 identify the searchable sample documents. Case-study IDs name fictional records described in summaries; their full documents are not bundled or indexed. No external source verifies these claims, and they are not equipment instructions.`},
 {id:'A2',title:'Local algorithms and presentation',origin:'lib/rag.ts · retrieve; app/visuals.tsx',text:'Concept groups, stop words, positive-score cutoff, stable tie order, reranking weights, expansion cap, graph multiplier and routing rules are author choices. Scores and graph positions are not probabilities or measured distances. The 1.8-second animation steps are presentation timing, not retrieval latency. The answer copies whole documents without checking whether they answer the question.'},
 {id:'A3',title:'Workload and storage model',origin:'app/enterprise.tsx · capacity section; app/visuals.tsx · CapacityChart',text:'Assume two logical search branches per wording, one answer per cache miss, a budget of 50 reranked pairs, 3,000 input and 500 output tokens, and a four-second mean generation time. Sliders choose traffic, phrasings and cache hit rate; none is measured. The separate storage example assumes 20 million vectors, 1,536 dimensions, four bytes per dimension and three full copies. That gives 122.88 GB per copy and 368.64 GB total, before other storage. These are decimal GB.'},
 {id:'A4',title:'Facilities architecture choices',origin:'lib/building-scenarios.ts; app/enterprise.tsx',text:'100 buildings and every asset, point, passage and edge count are hypothetical. Three query phrasings, 50 candidates, three graph hops / 200 nodes and three tool calls are illustrative limits, not industry standards. Pattern recommendations and operational suggestions are design judgments to validate on site-specific data. No building tools actually run here.'},
 {id:'A5',title:'Scope, privacy and quality',origin:'app/page.tsx; app/globals.css; lib/rag.ts',text:'Question processing runs locally with no model API call. Font loading can contact Google; opening references contacts their websites. All bundled documents are public to the browser. Collection filters are not access controls. Learning labs uses AI-authored examples and editable relevance judgments; no independent relevance benchmark, confidence calibration, automated contradiction check or domain-expert review has been completed. Lesson completion is saved locally; uploaded text and measured runs stay in memory until the lesson is left. Scores describe the selected examples and judgments; they do not establish performance on other datasets.'},
 {id:'A6',title:'Example data and measurements',origin:'lib/labs.ts; app/labs.tsx',text:`${examples.length} evaluation cases, suggested relevance grades, citation exercises, version conflicts, tenant records, the known malicious passage and community summary are AI-authored examples. They are not independent human labels. You can edit relevance grades. Chunk sizes are word counts; character count divided by four is only a token proxy. Graph tools execute local adjacency lookups. Queue inputs are hypothetical. Browser timing measures synchronous local retrieval only. Imported model measurements are user-reported. No trained model, production permission system or external agent tool runs in these labs.`},
];

export const gaps: {title:string;status:string;text:string}[] = [
 {title:'Measure retrieval and answer quality',status:'EVALUATION',text:`Learning labs computes recall and nDCG using ${examples.length} AI-authored sample questions, editable relevance grades and seven retrieval methods. Citation and conflicting-version exercises are included. For broader evaluation, supply independent relevance judgments and representative questions. Answer evaluation and domain-expert review are outside the scope of these examples.`},
 {title:'Explore ingestion and context',status:'INGESTION',text:'Load text or Markdown, adjust chunk boundaries and overlap, see which chunk holds the answer, and pack chunks into an estimated prompt budget. Token counts use character count divided by four. PDF/OCR parsing, learned embeddings, production indexing and model-specific tokenization are not included.'},
 {title:'Compare retrieval and generation',status:'MODEL COMPARISON',text:'Score BM25 and the six local approaches on all example questions, and export an evaluation kit. Import externally measured model results to compare retrieval quality, latency, tokens and cost. Learned encoders, trained rerankers and LLM generation run externally. Imported measurements are user-reported, not independently verified.'},
 {title:'Explore security and data freshness',status:'SECURITY',text:'Experiment with tenant filters, stale/deleted records, revision-scoped cache keys, a known malicious sample and citation-ID validation. These browser filters do not provide authentication, server-enforced access control, deletion propagation or general injection defense. All example records are public.'},
 {title:'Explore graph retrieval and tool calls',status:'GRAPH & TOOLS',text:'Explore typed edges with source passages, multiple hops, call budgets, simulated failures and a pre-written summary. Compare fixed traversal with rule-directed pruning. Traversal uses local rules. Model-directed agents, community detection, generated reports and external tools are not included.'},
 {title:'Measure latency and queueing',status:'OPERATIONS',text:'Measure local retrieval p50/p95 and inspect a simulated FIFO queue. These measurements do not cover service load, provider quotas or production monitoring. Browser timing excludes generation and network traffic.'},
];
